Add a bit more description for community
Abbe98/wikidata-sign-language-browser pull request #1
Opened 2018-10-07 12:53 UTC by ernoma

I think there should be more detailed description for the community. It is also Hacktoberfest, https://hacktoberfest.digitalocean.com/ ;) There are also social impact projects: https://www.hotosm.org/updates/hacktoberfest-a-call-for-contributing-to-social-impact-projects/.

2018-10-16 05:47 UTC, Abbe98 commented
@ernoma this is awesome thanks! Images is key in this type of application's README.

Just a minor change request from my side. It would be great if the links where in Markdown. The common behavior in Github README's is that links open in the current window anyway. 

Have a great Hacktoberfest :smiley: :jack_o_lantern:

2018-10-16 05:49 UTC, Abbe98 requested changes
Markown for links and images.

2018-10-16 05:49 UTC, Abbe98 commented on README.md
> +<img src="docs/word_list.png" width="676">
Images too in markdown btw

2018-10-21 09:08 UTC, ernoma commented
Alright, the links and images are now in Markdown. I think GitHub Markdown doesn't support image resizing, so I resized the images.

2018-10-21 20:30 UTC, Abbe98 commented
@ernoma Thank you very much for the contribution!

2018-10-21 20:30 UTC, merged